# Gradle properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# Check https://fabricmc.net/develop for the current recommended versions
# whenever you bump the Minecraft version.
minecraft_version=1.21.1
loader_version=0.16.14
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=net.iamsocool
archives_base_name=actionhud

# Dependencies
fabric_version=0.116.15+1.21.1
